apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
  {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
      containers:
      - image: linuxserver/radarr:latest
        imagePullPolicy: Always
        name: radarr
        env:
{{ toYaml .Values.env | indent 12 }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
