apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jellyfin.dataPvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi