apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
  {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
      containers:
      - image: linuxserver/jackett:latest
        imagePullPolicy: Always
        name: jackett
        env:
{{ toYaml .Values.env | indent 12 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 9117
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - name: http
          containerPort: 9117
          protocol: TCP
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
