# Storage values
storage:
  capacity:
    storage: "500Gi"
  hostPath: /mnt/media/media
  pvName: "media-ssd-pv"
  pvcName: &storagePvcName "media-ssd-pvc"

# Bazarr values
bazarr:
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

  ingress:
    hostname: bazarr.radi

  nodeSelector:
    kubernetes.io/arch: amd64

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  svcName: bazarr-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName

  volumeMounts:
    - name: media-ssd
      mountPath: "/config"
      subPath: "configs/bazarr"
    - name: media-ssd
      mountPath: "/tv"
      subPath: "jellyfin/tv"
    - name: media-ssd
      mountPath: "/movies"
      subPath: "jellyfin/movies"

# Jackett values
jackett:
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

  ingress:
    hostname: jackett.radi

  nodeSelector:
    kubernetes.io/arch: amd64

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  svcName: jackett-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName

  volumeMounts:
    - name: "media-ssd"
      mountPath: "/config"
      subPath: "configs/jackett"
    - name: "media-ssd"
      mountPath: "/downloads"
      subPath: "downloads/jackett"

# Jellyfin values
jellyfin:
  hostname: jellyfin.radi
  svcName: jellyfin-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName


  volumeMounts:
    - name: "media-ssd"
      mountPath: "/config"
      subPath: "configs/jellyfin"
    - name: "media-ssd"
      mountPath: "/data/movies"
      subPath: "jellyfin/movies"
    - name: "media-ssd"
      mountPath: "/data/tv"
      subPath: "jellyfin/tv"

# Radarr values
radarr:
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

  ingress:
    hostname: radarr.radi

  nodeSelector:
    kubernetes.io/arch: amd64

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  svcName: radarr-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName

  volumeMounts:
    - name: media-ssd
      mountPath: "/config"
      subPath: "configs/radarr"
    - name: media-ssd
      mountPath: "/downloads/transmission"
      subPath: "downloads/transmission"
    - name: media-ssd
      mountPath: "/movies"
      subPath: "jellyfin/movies"

# Sonarr Values
sonarr:
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

  ingress:
    hostname: sonarr.radi

  nodeSelector:
    kubernetes.io/arch: amd64

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  svcName: sonarr-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName

  volumeMounts:
    - name: media-ssd
      mountPath: "/config"
      subPath: "configs/sonarr"
    - name: media-ssd
      mountPath: "/downloads/transmission"
      subPath: "downloads/transmission"
    - name: media-ssd
      mountPath: "/tv"
      subPath: "jellyfin/tv"

# Transmission-openvpn values
transmission-openvpn:
  env:
    - name: OPENVPN_PROVIDER
      value: "PIA" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
    - name: OPENVPN_USERNAME
      valueFrom: # Reference to the secret | openvpn.username
        secretKeyRef:
          name: "openvpn"
          key: "username"
    - name: OPENVPN_PASSWORD
      valueFrom: # Reference to the secret | openvpn.password
        secretKeyRef:
          name: "openvpn"
          key: "password"
    - name: OPENVPN_CONFIG
      value: "ca_montreal" # Country where we want to download over VPN
    - name: LOCAL_NETWORK
      value: "192.168.1.0/24"
    - name: TRANSMISSION_PEER_PORT
      value: "47444"
    - name: TRANSMISSION_DOWNLOAD_DIR
      value: "/downloads/transmission"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

  ingress:
    hostname: transmission.radi

  nodeSelector:
    kubernetes.io/arch: amd64

  svcName: transmission-openvpn-svc

  volumes:
    - name: media-ssd
      persistentVolumeClaim:
        claimName: *storagePvcName

  volumeMounts:
    - name: "media-ssd"
      mountPath: "/data"
      subPath: "configs/transmission-data"
    - name: "media-ssd"
      mountPath: "/downloads/transmission"
      subPath: "downloads/transmission"

