apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  labels:
    app: transmission-openvpn
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: transmission-openvpn