apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage:  {{ .Values.storage.capacity.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.capacity.storage }}